package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.ecarinfo.db4j.table.DateTableField;
import com.ecarinfo.db4j.table.DateTableFieldImpl;

public class TAdminInfo extends AbstractTable {

	static {
		init();
	}

	private TAdminInfo(){
		super.tableName = "admin_info";
	}

	private TAdminInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TAdminInfo getInstance() {
		return new TAdminInfo();
	}

	public static final TAdminInfo getInstance(String aliasName) {
		return new TAdminInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("name", "name");
		allFieldMap.put("nickName", "nick_name");
		allFieldMap.put("password", "password");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 * | int(11)
	*/
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *用户姓名 | char(30)
	*/
	public final TableField<String> name = new TableFieldImpl<String>(this,"name","name","用户姓名");

	/**
	 *昵称 | char(30)
	*/
	public final TableField<String> nickName = new TableFieldImpl<String>(this,"nick_name","nickName","昵称");

	/**
	 * | char(32)
	*/
	public final TableField<String> password = new TableFieldImpl<String>(this,"password","password","");

	/**
	 *创建时间 | datetime
	*/
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 *更新时间 | datetime
	*/
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");


	private final TableField<?>[] allFields = new TableField<?>[] {id,name,nickName,password,createTime,updateTime};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TAdminInfo[table=admin_info]";
	}

}
