package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.ecarinfo.db4j.table.DateTableField;
import com.ecarinfo.db4j.table.DateTableFieldImpl;

public class TOrgCarInfo extends AbstractTable {

	static {
		init();
	}

	private TOrgCarInfo(){
		super.tableName = "org_car_info";
	}

	private TOrgCarInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TOrgCarInfo getInstance() {
		return new TOrgCarInfo();
	}

	public static final TOrgCarInfo getInstance(String aliasName) {
		return new TOrgCarInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("orgCode", "org_code");
		allFieldMap.put("carNo", "car_no");
		allFieldMap.put("carFrameNo", "car_frame_no");
		allFieldMap.put("carEngineNo", "car_engine_no");
		allFieldMap.put("certificate", "certificate");
		allFieldMap.put("carType", "car_type");
		allFieldMap.put("batNo", "bat_no");
		allFieldMap.put("status", "status");
		allFieldMap.put("isDelete", "is_delete");
		allFieldMap.put("queryType", "query_type");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 * | bigint(20)
	*/
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","");

	/**
	 *机构编号 | char(6)
	*/
	public final TableField<String> orgCode = new TableFieldImpl<String>(this,"org_code","orgCode","机构编号");

	/**
	 *车牌号 | char(7)
	*/
	public final TableField<String> carNo = new TableFieldImpl<String>(this,"car_no","carNo","车牌号");

	/**
	 *车架号 | char(32)
	*/
	public final TableField<String> carFrameNo = new TableFieldImpl<String>(this,"car_frame_no","carFrameNo","车架号");

	/**
	 *发动机号 | char(32)
	*/
	public final TableField<String> carEngineNo = new TableFieldImpl<String>(this,"car_engine_no","carEngineNo","发动机号");

	/**
	 *车辆证书编号 | char(32)
	*/
	public final TableField<String> certificate = new TableFieldImpl<String>(this,"certificate","certificate","车辆证书编号");

	/**
	 *车辆类型 | int(11)
	*/
	public final TableField<Integer> carType = new TableFieldImpl<Integer>(this,"car_type","carType","车辆类型");

	/**
	 *批次 | varchar(255)
	*/
	public final TableField<String> batNo = new TableFieldImpl<String>(this,"bat_no","batNo","批次");

	/**
	 *状态 | int(11)
	*/
	public final TableField<Integer> status = new TableFieldImpl<Integer>(this,"status","status","状态");

	/**
	 *是否删除 | tinyint(4)
	*/
	public final TableField<Boolean> isDelete = new TableFieldImpl<Boolean>(this,"is_delete","isDelete","是否删除");

	/**
	 *查询类型（1：实时查询，2：包年） | int(11)
	*/
	public final TableField<Integer> queryType = new TableFieldImpl<Integer>(this,"query_type","queryType","查询类型（1：实时查询，2：包年）");

	/**
	 *创建时间 | datetime
	*/
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 *更新时间 | datetime
	*/
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");


	private final TableField<?>[] allFields = new TableField<?>[] {id,orgCode,carNo,carFrameNo,carEngineNo,certificate,carType,batNo,status,isDelete,queryType,createTime,updateTime};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TOrgCarInfo[table=org_car_info]";
	}

}
