package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class TProvince extends AbstractTable {

	static {
		init();
	}

	private TProvince(){
		super.tableName = "province";
	}

	private TProvince(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TProvince getInstance() {
		return new TProvince();
	}

	public static final TProvince getInstance(String aliasName) {
		return new TProvince(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("name", "name");
		allFieldMap.put("simpleName", "simple_name");
		allFieldMap.put("keyTitle", "key_title");
		allFieldMap.put("status", "status");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 * | int(11)
	*/
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *省 | char(255)
	*/
	public final TableField<String> name = new TableFieldImpl<String>(this,"name","name","省");

	/**
	 *省简写 | char(255)
	*/
	public final TableField<String> simpleName = new TableFieldImpl<String>(this,"simple_name","simpleName","省简写");

	/**
	 *拼音首字符 | char(255)
	*/
	public final TableField<String> keyTitle = new TableFieldImpl<String>(this,"key_title","keyTitle","拼音首字符");

	/**
	 *是否有效，1为有效，0未无效 | int(11)
	*/
	public final TableField<Integer> status = new TableFieldImpl<Integer>(this,"status","status","是否有效，1为有效，0未无效");


	private final TableField<?>[] allFields = new TableField<?>[] {id,name,simpleName,keyTitle,status};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TProvince[table=province]";
	}

}
