package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.ecarinfo.db4j.table.DateTableField;
import com.ecarinfo.db4j.table.DateTableFieldImpl;

public class TQueryTaskDetail extends AbstractTable {

	static {
		init();
	}

	private TQueryTaskDetail(){
		super.tableName = "query_task_detail";
	}

	private TQueryTaskDetail(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TQueryTaskDetail getInstance() {
		return new TQueryTaskDetail();
	}

	public static final TQueryTaskDetail getInstance(String aliasName) {
		return new TQueryTaskDetail(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("queryTaskId", "query_task_id");
		allFieldMap.put("totalCount", "total_count");
		allFieldMap.put("validCount", "valid_count");
		allFieldMap.put("failCount", "fail_count");
		allFieldMap.put("trafficCount", "traffic_count");
		allFieldMap.put("startTime", "start_time");
		allFieldMap.put("endTime", "end_time");
		allFieldMap.put("createTime", "create_time");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 * | bigint(20)
	*/
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","");

	/**
	 * | int(11)
	*/
	public final TableField<Integer> queryTaskId = new TableFieldImpl<Integer>(this,"query_task_id","queryTaskId","");

	/**
	 *总查询数 | int(11)
	*/
	public final TableField<Integer> totalCount = new TableFieldImpl<Integer>(this,"total_count","totalCount","总查询数");

	/**
	 *有效查询数 | int(11)
	*/
	public final TableField<Integer> validCount = new TableFieldImpl<Integer>(this,"valid_count","validCount","有效查询数");

	/**
	 *失败查询数 | int(11)
	*/
	public final TableField<Integer> failCount = new TableFieldImpl<Integer>(this,"fail_count","failCount","失败查询数");

	/**
	 *本次任务的违章数 | int(11)
	*/
	public final TableField<Integer> trafficCount = new TableFieldImpl<Integer>(this,"traffic_count","trafficCount","本次任务的违章数");

	/**
	 *查询开始时间 | datetime
	*/
	public final DateTableField<Date> startTime = new DateTableFieldImpl<Date>(this,"start_time","startTime","查询开始时间");

	/**
	 *查询结束时间 | datetime
	*/
	public final DateTableField<Date> endTime = new DateTableFieldImpl<Date>(this,"end_time","endTime","查询结束时间");

	/**
	 * | datetime
	*/
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");


	private final TableField<?>[] allFields = new TableField<?>[] {id,queryTaskId,totalCount,validCount,failCount,trafficCount,startTime,endTime,createTime};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TQueryTaskDetail[table=query_task_detail]";
	}

}
