package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.ecarinfo.db4j.table.DateTableField;
import com.ecarinfo.db4j.table.DateTableFieldImpl;

public class TQueryTraffic extends AbstractTable {

	static {
		init();
	}

	private TQueryTraffic(){
		super.tableName = "query_traffic";
	}

	private TQueryTraffic(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TQueryTraffic getInstance() {
		return new TQueryTraffic();
	}

	public static final TQueryTraffic getInstance(String aliasName) {
		return new TQueryTraffic(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("queryId", "query_id");
		allFieldMap.put("trafficId", "traffic_id");
		allFieldMap.put("createTime", "create_time");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 * | bigint(20)
	*/
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","");

	/**
	 *查询id | bigint(20)
	*/
	public final TableField<Long> queryId = new TableFieldImpl<Long>(this,"query_id","queryId","查询id");

	/**
	 *关联的违章 | bigint(20)
	*/
	public final TableField<Long> trafficId = new TableFieldImpl<Long>(this,"traffic_id","trafficId","关联的违章");

	/**
	 *创建时间 | datetime
	*/
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");


	private final TableField<?>[] allFields = new TableField<?>[] {id,queryId,trafficId,createTime};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TQueryTraffic[table=query_traffic]";
	}

}
