package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.ecarinfo.db4j.table.DateTableField;
import com.ecarinfo.db4j.table.DateTableFieldImpl;

public class TQueryTask extends AbstractTable {

	static {
		init();
	}

	private TQueryTask(){
		super.tableName = "query_task";
	}

	private TQueryTask(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TQueryTask getInstance() {
		return new TQueryTask();
	}

	public static final TQueryTask getInstance(String aliasName) {
		return new TQueryTask(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("name", "name");
		allFieldMap.put("operatorId", "operator_id");
		allFieldMap.put("orgCode", "org_code");
		allFieldMap.put("taskDetail", "task_detail");
		allFieldMap.put("taskType", "task_type");
		allFieldMap.put("status", "status");
		allFieldMap.put("orgScheduleId", "org_schedule_id");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 * | int(11)
	*/
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *自定义任务名称 | varchar(255)
	*/
	public final TableField<String> name = new TableFieldImpl<String>(this,"name","name","自定义任务名称");

	/**
	 *操作员 | int(11)
	*/
	public final TableField<Integer> operatorId = new TableFieldImpl<Integer>(this,"operator_id","operatorId","操作员");

	/**
	 *机构编号 | char(6)
	*/
	public final TableField<String> orgCode = new TableFieldImpl<String>(this,"org_code","orgCode","机构编号");

	/**
	 *任务描述 | varchar(255)
	*/
	public final TableField<String> taskDetail = new TableFieldImpl<String>(this,"task_detail","taskDetail","任务描述");

	/**
	 *任务类型 | int(11)
	*/
	public final TableField<Integer> taskType = new TableFieldImpl<Integer>(this,"task_type","taskType","任务类型");

	/**
	 *任务状态 | int(11)
	*/
	public final TableField<Integer> status = new TableFieldImpl<Integer>(this,"status","status","任务状态");

	/**
	 *机构调度id | int(11)
	*/
	public final TableField<Integer> orgScheduleId = new TableFieldImpl<Integer>(this,"org_schedule_id","orgScheduleId","机构调度id");

	/**
	 *创建时间 | datetime
	*/
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 *更新时间 | datetime
	*/
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");


	private final TableField<?>[] allFields = new TableField<?>[] {id,name,operatorId,orgCode,taskDetail,taskType,status,orgScheduleId,createTime,updateTime};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TQueryTask[table=query_task]";
	}

}
