package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.ecarinfo.db4j.table.DateTableField;
import com.ecarinfo.db4j.table.DateTableFieldImpl;

public class TQueryArea extends AbstractTable {

	static {
		init();
	}

	private TQueryArea(){
		super.tableName = "query_area";
	}

	private TQueryArea(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TQueryArea getInstance() {
		return new TQueryArea();
	}

	public static final TQueryArea getInstance(String aliasName) {
		return new TQueryArea(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("orgCode", "org_code");
		allFieldMap.put("provinceId", "province_id");
		allFieldMap.put("cityId", "city_id");
		allFieldMap.put("provinceName", "province_name");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("cityName", "city_name");
		allFieldMap.put("createTime", "create_time");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 * | int(11)
	*/
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *机构编码 | char(6)
	*/
	public final TableField<String> orgCode = new TableFieldImpl<String>(this,"org_code","orgCode","机构编码");

	/**
	 *省份id | int(11)
	*/
	public final TableField<Integer> provinceId = new TableFieldImpl<Integer>(this,"province_id","provinceId","省份id");

	/**
	 *城市id | int(11)
	*/
	public final TableField<Integer> cityId = new TableFieldImpl<Integer>(this,"city_id","cityId","城市id");

	/**
	 *省份名称 | char(30)
	*/
	public final TableField<String> provinceName = new TableFieldImpl<String>(this,"province_name","provinceName","省份名称");

	/**
	 * | datetime
	*/
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");

	/**
	 *城市名称 | char(30)
	*/
	public final TableField<String> cityName = new TableFieldImpl<String>(this,"city_name","cityName","城市名称");

	/**
	 *创建时间 | datetime
	*/
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");


	private final TableField<?>[] allFields = new TableField<?>[] {id,orgCode,provinceId,cityId,provinceName,updateTime,cityName,createTime};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TQueryArea[table=query_area]";
	}

}
