package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.ecarinfo.db4j.table.DateTableField;
import com.ecarinfo.db4j.table.DateTableFieldImpl;

public class TRalRole extends AbstractTable {

	static {
		init();
	}

	private TRalRole(){
		super.tableName = "ral_role";
	}

	private TRalRole(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TRalRole getInstance() {
		return new TRalRole();
	}

	public static final TRalRole getInstance(String aliasName) {
		return new TRalRole(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("roleId", "role_id");
		allFieldMap.put("name", "name");
		allFieldMap.put("message", "message");
		allFieldMap.put("status", "status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 *角色id | int(11)
	*/
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"role_id","roleId","角色id");
	public final TableField<Integer> roleId = new TableFieldImpl<Integer>(this,"role_id","roleId","角色id");

	/**
	 *角色名称 | varchar(255)
	*/
	public final TableField<String> name = new TableFieldImpl<String>(this,"name","name","角色名称");

	/**
	 * 角色描述 | varchar(255)
	*/
	public final TableField<String> message = new TableFieldImpl<String>(this,"message","message"," 角色描述");

	/**
	 *是否有效 | int(11)
	*/
	public final TableField<Integer> status = new TableFieldImpl<Integer>(this,"status","status","是否有效");

	/**
	 * | datetime
	*/
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 * | datetime
	*/
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");


	private final TableField<?>[] allFields = new TableField<?>[] {roleId,name,message,status,createTime,updateTime};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TRalRole[table=ral_role]";
	}

}
