package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class TRalUserRole extends AbstractTable {

	static {
		init();
	}

	private TRalUserRole(){
		super.tableName = "ral_user_role";
	}

	private TRalUserRole(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TRalUserRole getInstance() {
		return new TRalUserRole();
	}

	public static final TRalUserRole getInstance(String aliasName) {
		return new TRalUserRole(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("roleId", "role_id");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 *用户id | int(11)
	*/
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"user_id","userId","用户id");
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户id");

	/**
	 *角色id | int(11)
	*/
	public final TableField<Integer>  pk1 = new TableFieldImpl<Integer>(this,"role_id","roleId","角色id");
	public final TableField<Integer> roleId = new TableFieldImpl<Integer>(this,"role_id","roleId","角色id");


	private final TableField<?>[] allFields = new TableField<?>[] {userId,roleId};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return false;
	}

	@Override
	public String toString() {
		return "TRalUserRole[table=ral_user_role]";
	}

}
