package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class TRalRoleResources extends AbstractTable {

	static {
		init();
	}

	private TRalRoleResources(){
		super.tableName = "ral_role_resources";
	}

	private TRalRoleResources(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TRalRoleResources getInstance() {
		return new TRalRoleResources();
	}

	public static final TRalRoleResources getInstance(String aliasName) {
		return new TRalRoleResources(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("roleId", "role_id");
		allFieldMap.put("resourcesId", "resources_id");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 *角色id | int(11)
	*/
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"role_id","roleId","角色id");
	public final TableField<Integer> roleId = new TableFieldImpl<Integer>(this,"role_id","roleId","角色id");

	/**
	 *资源id | int(11)
	*/
	public final TableField<Integer>  pk1 = new TableFieldImpl<Integer>(this,"resources_id","resourcesId","资源id");
	public final TableField<Integer> resourcesId = new TableFieldImpl<Integer>(this,"resources_id","resourcesId","资源id");


	private final TableField<?>[] allFields = new TableField<?>[] {roleId,resourcesId};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return false;
	}

	@Override
	public String toString() {
		return "TRalRoleResources[table=ral_role_resources]";
	}

}
