package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.ecarinfo.db4j.table.DateTableField;
import com.ecarinfo.db4j.table.DateTableFieldImpl;

public class TSpiInfo extends AbstractTable {

	static {
		init();
	}

	private TSpiInfo(){
		super.tableName = "spi_info";
	}

	private TSpiInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSpiInfo getInstance() {
		return new TSpiInfo();
	}

	public static final TSpiInfo getInstance(String aliasName) {
		return new TSpiInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("name", "name");
		allFieldMap.put("enName", "en_name");
		allFieldMap.put("nodeUrl", "node_url");
		allFieldMap.put("ruleUrl", "rule_url");
		allFieldMap.put("trafficUrl", "traffic_url");
		allFieldMap.put("status", "status");
		allFieldMap.put("spiKey", "spi_key");
		allFieldMap.put("userName", "user_name");
		allFieldMap.put("password", "password");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 * | int(11)
	*/
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *spi名称 | varchar(255)
	*/
	public final TableField<String> name = new TableFieldImpl<String>(this,"name","name","spi名称");

	/**
	 *英文名称描述 | varchar(255)
	*/
	public final TableField<String> enName = new TableFieldImpl<String>(this,"en_name","enName","英文名称描述");

	/**
	 *spi节点url | varchar(255)
	*/
	public final TableField<String> nodeUrl = new TableFieldImpl<String>(this,"node_url","nodeUrl","spi节点url");

	/**
	 *查询规则url | varchar(255)
	*/
	public final TableField<String> ruleUrl = new TableFieldImpl<String>(this,"rule_url","ruleUrl","查询规则url");

	/**
	 *获取违章数据url | varchar(255)
	*/
	public final TableField<String> trafficUrl = new TableFieldImpl<String>(this,"traffic_url","trafficUrl","获取违章数据url");

	/**
	 *spi状态 | int(11)
	*/
	public final TableField<Integer> status = new TableFieldImpl<Integer>(this,"status","status","spi状态");

	/**
	 *key | varchar(255)
	*/
	public final TableField<String> spiKey = new TableFieldImpl<String>(this,"spi_key","spiKey","key");

	/**
	 *登录名 | varchar(255)
	*/
	public final TableField<String> userName = new TableFieldImpl<String>(this,"user_name","userName","登录名");

	/**
	 *密码 | varchar(255)
	*/
	public final TableField<String> password = new TableFieldImpl<String>(this,"password","password","密码");

	/**
	 *创建时间 | datetime
	*/
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 *更新时间 | datetime
	*/
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");


	private final TableField<?>[] allFields = new TableField<?>[] {id,name,enName,nodeUrl,ruleUrl,trafficUrl,status,spiKey,userName,password,createTime,updateTime};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TSpiInfo[table=spi_info]";
	}

}
