package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.ecarinfo.db4j.table.DateTableField;
import com.ecarinfo.db4j.table.DateTableFieldImpl;

public class TSpiMoney extends AbstractTable {

	static {
		init();
	}

	private TSpiMoney(){
		super.tableName = "spi_money";
	}

	private TSpiMoney(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSpiMoney getInstance() {
		return new TSpiMoney();
	}

	public static final TSpiMoney getInstance(String aliasName) {
		return new TSpiMoney(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("type", "type");
		allFieldMap.put("name", "name");
		allFieldMap.put("spiId", "spi_id");
		allFieldMap.put("money", "money");
		allFieldMap.put("status", "status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 * | int(11)
	*/
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *收费类型(1:按单个请求，2.按年，3：按月，4：按日) | int(11)
	*/
	public final TableField<Integer> type = new TableFieldImpl<Integer>(this,"type","type","收费类型(1:按单个请求，2.按年，3：按月，4：按日)");

	/**
	 *收费描述 | char(200)
	*/
	public final TableField<String> name = new TableFieldImpl<String>(this,"name","name","收费描述");

	/**
	 *spi_info的id | int(11)
	*/
	public final TableField<Integer> spiId = new TableFieldImpl<Integer>(this,"spi_id","spiId","spi_info的id");

	/**
	 *收费(元) | float
	*/
	public final TableField<Float> money = new TableFieldImpl<Float>(this,"money","money","收费(元)");

	/**
	 *状态 | int(11)
	*/
	public final TableField<Integer> status = new TableFieldImpl<Integer>(this,"status","status","状态");

	/**
	 *创建时间 | datetime
	*/
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 *更新时间 | datetime
	*/
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");


	private final TableField<?>[] allFields = new TableField<?>[] {id,type,name,spiId,money,status,createTime,updateTime};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TSpiMoney[table=spi_money]";
	}

}
