package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.ecarinfo.db4j.table.DateTableField;
import com.ecarinfo.db4j.table.DateTableFieldImpl;

public class TTrafficInfo extends AbstractTable {

	static {
		init();
	}

	private TTrafficInfo(){
		super.tableName = "traffic_info";
	}

	private TTrafficInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TTrafficInfo getInstance() {
		return new TTrafficInfo();
	}

	public static final TTrafficInfo getInstance(String aliasName) {
		return new TTrafficInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("carNo", "car_no");
		allFieldMap.put("carType", "car_type");
		allFieldMap.put("trafficDetail", "traffic_detail");
		allFieldMap.put("trafficCity", "traffic_city");
		allFieldMap.put("trafficLocation", "traffic_location");
		allFieldMap.put("trafficTime", "traffic_time");
		allFieldMap.put("archive", "archive");
		allFieldMap.put("code", "code");
		allFieldMap.put("uniqueKey", "unique_key");
		allFieldMap.put("scores", "scores");
		allFieldMap.put("status", "status");
		allFieldMap.put("money", "money");
		allFieldMap.put("createTime", "create_time");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 * | bigint(20)
	*/
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","");

	/**
	 *车牌号 | char(7)
	*/
	public final TableField<String> carNo = new TableFieldImpl<String>(this,"car_no","carNo","车牌号");

	/**
	 *车型 | int(11)
	*/
	public final TableField<Integer> carType = new TableFieldImpl<Integer>(this,"car_type","carType","车型");

	/**
	 *违章描述 | varchar(255)
	*/
	public final TableField<String> trafficDetail = new TableFieldImpl<String>(this,"traffic_detail","trafficDetail","违章描述");

	/**
	 *违章城市 | char(50)
	*/
	public final TableField<String> trafficCity = new TableFieldImpl<String>(this,"traffic_city","trafficCity","违章城市");

	/**
	 *违章地点 | varchar(255)
	*/
	public final TableField<String> trafficLocation = new TableFieldImpl<String>(this,"traffic_location","trafficLocation","违章地点");

	/**
	 *违章时间 | datetime
	*/
	public final DateTableField<Date> trafficTime = new DateTableFieldImpl<Date>(this,"traffic_time","trafficTime","违章时间");

	/**
	 *文书号 | varchar(255)
	*/
	public final TableField<String> archive = new TableFieldImpl<String>(this,"archive","archive","文书号");

	/**
	 *违章代号 | varchar(255)
	*/
	public final TableField<String> code = new TableFieldImpl<String>(this,"code","code","违章代号");

	/**
	 *唯一标识一条违章记录=md5(base64(carNo+carType+detail+happenTime)) | char(32)
	*/
	public final TableField<String> uniqueKey = new TableFieldImpl<String>(this,"unique_key","uniqueKey","唯一标识一条违章记录=md5(base64(carNo+carType+detail+happenTime))");

	/**
	 *违章扣分 | int(11)
	*/
	public final TableField<Integer> scores = new TableFieldImpl<Integer>(this,"scores","scores","违章扣分");

	/**
	 *处理状态(0 未处理  1 己处理) | int(11)
	*/
	public final TableField<Integer> status = new TableFieldImpl<Integer>(this,"status","status","处理状态(0 未处理  1 己处理)");

	/**
	 *违章罚款 | float
	*/
	public final TableField<Float> money = new TableFieldImpl<Float>(this,"money","money","违章罚款");

	/**
	 *创建时间 | datetime
	*/
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");


	private final TableField<?>[] allFields = new TableField<?>[] {id,carNo,carType,trafficDetail,trafficCity,trafficLocation,trafficTime,archive,code,uniqueKey,scores,status,money,createTime};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TTrafficInfo[table=traffic_info]";
	}

}
