package com.ecarinfo.traffic.persist.tables;
import com.ecarinfo.db4j.table.AllField;
import com.ecarinfo.db4j.table.AbstractTable;
import com.ecarinfo.db4j.table.TableField;
import com.ecarinfo.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.ecarinfo.db4j.table.DateTableField;
import com.ecarinfo.db4j.table.DateTableFieldImpl;

public class TUpdateFlag extends AbstractTable {

	static {
		init();
	}

	private TUpdateFlag(){
		super.tableName = "update_flag";
	}

	private TUpdateFlag(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TUpdateFlag getInstance() {
		return new TUpdateFlag();
	}

	public static final TUpdateFlag getInstance(String aliasName) {
		return new TUpdateFlag(aliasName);
	}

	private static Map<String, String> allFieldMap;// = new HashMap<String, String>();
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("name", "name");
		allFieldMap.put("maxId", "max_id");
		allFieldMap.put("lastUpdateTime", "last_update_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("createTime", "create_time");

	}

	@Override
	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	@SuppressWarnings("rawtypes")
	@Override
	public TableField allField() {
		return all;
	}

	/**
	 * | int(11)
	*/
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *名称 | char(50)
	*/
	public final TableField<String> name = new TableFieldImpl<String>(this,"name","name","名称");

	/**
	 *最大id | bigint(20)
	*/
	public final TableField<Long> maxId = new TableFieldImpl<Long>(this,"max_id","maxId","最大id");

	/**
	 *最后更新时间 | datetime
	*/
	public final DateTableField<Date> lastUpdateTime = new DateTableFieldImpl<Date>(this,"last_update_time","lastUpdateTime","最后更新时间");

	/**
	 *更新时间 | datetime
	*/
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");

	/**
	 *创建时间 | datetime
	*/
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");


	private final TableField<?>[] allFields = new TableField<?>[] {id,name,maxId,lastUpdateTime,updateTime,createTime};

	@Override
	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	@Override
	public TableField<?> getPK() {
		return pk;
	}

	@Override
	public final boolean isAutoGeneratedPK() {
		return true;
	}

	@Override
	public String toString() {
		return "TUpdateFlag[table=update_flag]";
	}

}
